### ISSUE TITLE
ROHAN4600_0936の「羞月閉花」の読み方

### ISSUE THREAD

**Issue by pipolll** [mmorise/rohan4600#1]
ROHAN4600_0936
```
ROHAN4600_0936:フィオレンティーノは羞月閉花(しゅうかへいげつ)で、非(ひ)の打(う)ち所(どころ)がない。,フィオレンティーノワシュウカヘイゲツデ、ヒノウチドコロガナイ。
```
の「羞月閉花」について、.txtファイルや.pdfにおける読みは「しゅうかへいげつ」となっているのですが、
この漢字の並びにおける読みは「しゅうげつへいか」ではないでしょうか？
また、朗読をする際は現在の読み仮名である「しゅうかへいげつ」（羞花閉月）と、
現在の表記である「しゅうげつへいか」（羞月閉花）の
どちらで読めばよいでしょうか？

**Comment by mmorise** [comment]
ありがとうございます．
こちらは，読み仮名に合わせ「しゅうかへいげつ」で読むことを想定しておりました．漢字のミスなので，修正します．

**Comment by pipolll** [comment]
ご回答・ご対応ありがとうございました。読み仮名に合わせて読むようにします。
